<?php

/**
 * @file
 * Provides an address entry entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function address_book_theme() {
  return [
    'address_entry' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for address entry templates.
 *
 * Default template: address-entry.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the address entry information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_address_entry(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
